## Neural Network Supervised Learning 의 기본과정

1. dataset
> load, 전처리
2. 모델 생성
3. loss function 정의
4. 모델을 통한 예측
5. 예측값과 target값과의 비교
6. loss로 부터 back propagation을 통한 gradient 갱신
7. optimizer를 통한 parameter 갱신
8. 손실값을 측정하며 충분히 낮으면 학습 종료
> 모델과 가중치값 저장

## 기본적인 pytorch package
1. torch
2. torch.autograd
3. torch.nn
> torch.nn.functional 에서 손실함수, 활성화함수,레이어, 데이터 구조 등 포함
4. torch.optim
> SGD (stochastic gradient descent) 기반 다양한 optimizer로 parameter 최적화
5. torch.utils.data
> SGD 반복연산을 위한 미니배치용 유틸함수
6. torch.onnx (Open Neural Network eXchange)
> model export 시 사용

## torch.tensor
> data, device, requires_grad, dtype 등의 속성을 정의한 tensor

In [10]:
import torch

t = torch.tensor([1,2,3],device = 'cpu', requires_grad = False, dtype = torch.float64)
device = 'cuda' if torch.cuda.is_available() else 'cpu' 
t = t.to(device)
print(t)



tensor([1., 2., 3.], device='cuda:0', dtype=torch.float64)


tensor([[1., 2.],
        [3., 4.]])

## torch tensor 생성 기본함수

In [31]:
# torch tensor 생성 기본함수 numpy와 유사한 형식
arr = [[1,2],[3,4]]
t1 = torch.tensor(arr)
t1 = torch.Tensor(t1)
print(t1)

t2 = torch.ones((2,2))

t3 = torch.rand(2,2)
print(t2,t3,sep='\n')

torch.manual_seed(9)
t4 = torch.rand(2,2)
torch.manual_seed(9)
t5 = torch.rand(2,2)
print(t4,t5,sep='\n')

# 단위 행렬
t6 = torch.eye(3,dtype = torch.double)
t7=torch.arange(5)
print(t6,t7,sep='\n')

tensor([[1, 2],
        [3, 4]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.9180, 0.9310],
        [0.2604, 0.9534]])
tensor([[0.6558, 0.3020],
        [0.4799, 0.7774]])
tensor([[0.6558, 0.3020],
        [0.4799, 0.7774]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64)
tensor([0, 1, 2, 3, 4])


## torch.tensor의 dimension 관련 함수

In [49]:
# torch.tensor dimension 관련함수
t = torch.arange(6)
# 형태, size 출력
print(t.shape)
# 다양한 reshape함수
t = t.reshape(2,-1) # = t.reshape(2,3) = t.view(2,3)
print(t,t.shape)
# 차원 증가 및 축소
t = t.unsqueeze(dim = 1) # 두번 째 차원 하나 추가
print(t,t.shape)
# squeeze는 차원이 1인 축을 삭제하는 함수
# batch가 1인 tensor의 경우 batch차원을 없앨 수도 있으니 주의
t = t.squeeze(dim = 1)
print(t,t.shape)
t1 = torch.zeros((2,3))
t2 = torch.ones((2,3))
print(t1,t2,sep='\n')
t3 = torch.cat([t1,t2],dim = 0) # dim = 0 4x3 dim = 1 2x6
t3


torch.Size([6])
tensor([[0, 1, 2],
        [3, 4, 5]]) torch.Size([2, 3])
tensor([[[0, 1, 2]],

        [[3, 4, 5]]]) torch.Size([2, 1, 3])
tensor([[0, 1, 2],
        [3, 4, 5]]) torch.Size([2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [50]:
print("test")

test
